steps:
- name: 'gcr.io/$PROJECT_ID/scala-sbt'
  args: ['clean', 'docker:stage']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/space-rocks:latest', '.']
  dir: 'target/docker/stage'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment', 'space-rocks', 'space-rocks=gcr.io/$PROJECT_ID/space-rocks:latest']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=space-rocks-cluster'


#images: ['gcr.io/$PROJECT_ID/space-rocks']