steps:
- name: 'gcr.io/$PROJECT_ID/scala-sbt'
  args: ['clean', 'docker:stage']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/space-rocks', '.']
  dir: 'target/docker/stage'
images: ['gcr.io/$PROJECT_ID/space-rocks']